# Generated by Django 6.0.3 on 2026-04-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0007_alter_assessment_assessment_type_alter_user_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
