# Generated by Django 6.0.3 on 2026-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0007_notification'),
        ('evalify_app', '0008_delete_studentprofile'),
    ]

    operations = [
    ]
